[workspace]
members = [
  "faer-core",
  "faer-cholesky",
  "faer-lu",
  "faer-qr",
  "faer",
  "faer-bench",
  "xtask",
]

[profile.release]
debug-assertions = true
overflow-checks = true

[profile.bench]
debug-assertions = false
overflow-checks = false
